### ISSUE TITLE
Possible issue on IOS 13.2.3 - Invalid Bundle Selection

### ISSUE THREAD

**Issue by ghost** [Skittyblock/WallpaperLoader#1]
Selection in aware wallpaper selector is greyed out and attempting to select the bundle for use results in no image displayed in preview. 

If selection is set then setting fails back to previous wallpaper selection.

Also, this is on IOS 13.2.3, iPhone X

**Comment by Skittyblock** [comment]
So... were you just using a custom-made broken bundle?
