### ISSUE TITLE
Prevent "Zooming in" of custom wallpapers 

### ISSUE THREAD

**Issue by mmshivesh** [Skittyblock/WallpaperLoader#3]
While making wallpapers and loading them into settings, The wallpapers zoom. Is there a way to prevent this behavior? I think iOS does it using the logical screen class argument in the wallpaper.plist?

**Comment by ghost** [comment]
Are the pictures that you’re using the correct resolution?

I have no idea what that resolution is supposed to be, but I’m sure it’s somewhere in the repo.

**Comment by Skittyblock** [comment]
1.1 attempts to fix this issue by caching resized images, so I'm going to close this for now.

**Comment by mmshivesh** [comment]
Can attest to this. The zoom in problem has been vastly mitigated with the move to v1.1. Thanks!
