### ISSUE TITLE
Setting Crashes When Trying to Set Live Wallpaper on 13.5

### ISSUE THREAD

**Issue by ohlesl1e** [Skittyblock/WallpaperLoader#4]
Setting app crashed when I tried to set a live wallpaper from DynaWall V3.0
Not sure if it's from this end or DynaWall's end

**Comment by Skittyblock** [comment]
Do you have a crash log?

**Comment by ohlesl1e** [comment]
It says in the console:
Error writing video file to 'file:///var/mobile/Library/SpringBoard/OriginalLockVideo.mov': The file “Default.m4v” couldn’t be opened because there is no such file.

I looked in the WallpaperLoader folder, the file is not there. I'm guessing DynaWall didn't make the file?

**Comment by Skittyblock** [comment]
Sounds like a DynaWall bug. It didn't properly create a wallpaper bundle.
