### ISSUE TITLE
Selecting wallpaper crashes the settings app.

### ISSUE THREAD

**Issue by Ryanizleee** [Skittyblock/WallpaperLoader#6]
I am using Edictus to create wallpapers and when I try to select a wallpaper my settings app crashed instantly.
This happened with the later version of WallpaperLoader which is version 1.1 and 1.1-1.
I downgraded back to version 1.0 and it works fine.
My device is iPhone XS Max on iOS 13.5 running unc0ver 5.3.1
I have attached a crash log, hopefully it helps.

[Preferences-2020-09-30-210904.symbolicated.txt](https://github.com/Skittyblock/WallpaperLoader/files/5305779/Preferences-2020-09-30-210904.symbolicated.txt)

**Comment by Iristallite** [comment]
The same thing happened to me on an iPad mini 5

here's TWELVE logs from cr4shed
[Archive.zip](https://github.com/Skittyblock/WallpaperLoader/files/5318050/Archive.zip)

**Comment by Skittyblock** [comment]
Fixed in 1.1.1
